util/helpers.py

os.replace does not work if the source and destination is not in the same file system. 
Eg: "/tmp" might be in a different file system to "~/.local/share/TinyDecred/"
This changes "os.replace" to "shutil.move"

use shutil.move insted of os.replace

---

README.md

Secp256k1 is an elliptic curve, not an exercise machine.

Fix misspelled/wrong word

---

pydecred/README.md

Fix some of the examples in `pydecred/README.md`:
1. fix the `DcrdataClient` import path;
2. remove all `get` calls, they're not in the API;
3. work around the syntax error caused by trying to use the `in` language keyword
in a dotted chain.

Fix some examples in PyDecred's README

---

.coveragerc
.gitignore
crypto/crypto.py
crypto/opcode.py
crypto/secp256k1/field.py
pydecred/txscript.py
pydecred/vsp.py
pydecred/wire/msgblock.py
pydecred/wire/msgtx.py
pydecred/wire/wire.py
tests/unit/crypto/test_crypto.py
tests/unit/crypto/test_mnemonic.py
tests/unit/pydecred/test_calc.py
tests/unit/pydecred/test_pydecred.py
tests/unit/pydecred/test_txscript.py
tests/unit/pydecred/wire/test_msgtx.py
tests/unit/pydecred/wire/test_wire.py
tests/unit/util/test_encode.py
util/encode.py
util/helpers.py
wallet/api.py

This is a first pass at improving test coverage. Part of #38.
I added a `.coveragerc` config file which, among other things, excludes the test files themselves from coverage. This brought the overall coverage down from a theoretical 74% to a more realistic 70%.
It also excludes lines raising several errors: `AssertionError`, `NotImplementedError`, `CrazyKeyError` and `ParameterRangeError`. I then changed a number of exceptions to `AssertionError` and `NotImplementedError`, let me know if this approach makes sense.
I manually excluded some minor methods from coverage with the `nocover` comment.
I also added and extended several tests, which also increased coverage. It currently stands at 71%.
Here is the command I'm using (it needs the `pytest-cov` plugin), run from the directory above the …

Tests: first pass at improving coverage

---

util/chains.py

Must've snuck in during database work. Problematic and unneeded.

pydecred: remove config from nets module

---

decred/decred/dcr/account.py

closes #62 
Using a generator causes problems when a revocation happens. Changing this to a list solves this.

revocations: Store revocation txid in list

---

.gitignore
CONTRIBUTING.md
decred/coverage-html.sh
decred/pyproject.toml

Add an easy way to get test coverage by using a pytest plugin. Part of #38.
- Add the `pytest-cov` plugin to `pyproject.toml` as a dev. dependency.
- Create the `./decred/coverage-html.sh` script to run tests and generate an HTML coverage report.
- Mention the script in the `CONTRIBUTING.md` doc.

tests: add html coverage script

---

decred/.coveragerc
decred/decred/crypto/crypto.py
decred/decred/dcr/nets.py
decred/decred/dcr/wire/msgblock.py
decred/decred/dcr/wire/msgtx.py
decred/decred/util/database.py
decred/decred/wallet/accounts.py
decred/tests/unit/crypto/test_crypto.py
decred/tests/unit/dcr/test_nets.py
decred/tests/unit/dcr/wire/test_msgblock.py
decred/tests/unit/dcr/wire/test_msgtx.py
decred/tests/unit/dcr/wire/test_wire.py
decred/tests/unit/util/test_database.py
decred/tests/unit/util/test_encode.py

Part of #38.
Increase test coverage of various modules:
- `crypto/cripto.py`;
- `msgblock.py`, `msgtx.py` and `wire.py` in `dcr/wire`;
- `util/database.py`.
Additionally:
- make the HTML report show which tests exercise which lines of code;
- refactor the `dcr/nets.py` file and add a test for it;
- simplify the `MsgTx.decodeWitness` method in `dcr/wire/msgtx.py`;
- use `ValueError` in `util/database.py`.

tests: increase coverage

---

.github/workflows/python.yml
decred/.flake8
decred/decred/crypto/crypto.py
decred/decred/crypto/mnemonic.py
decred/decred/crypto/rando.py
decred/decred/crypto/secp256k1/curve.py
decred/decred/crypto/secp256k1/field.py
decred/decred/dcr/account.py
decred/decred/dcr/calc.py
decred/decred/dcr/dcrdata.py
decred/decred/dcr/nets/__init__.py
decred/decred/dcr/rpc.py
decred/decred/dcr/txscript.py
decred/decred/dcr/vsp.py
decred/decred/dcr/wire/msgtx.py
decred/decred/wallet/wallet.py
decred/examples/plot_ticket_price.py
decred/pyproject.toml
decred/tests/benchmark/util/test_database_benchmark.py
decred/tests/integration/dcr/test_rpc.py
decred/tests/unit/dcr/test_txscript.py
tinywallet/.flake8
tinywallet/poetry.lock
tinywallet/pyproject.toml
tinywallet/tests/unit/no_tests_yet.py
tinywallet/tests/unit/test_placeholder.py
tinywallet/tinywallet/app.py
tinywallet/tinywallet/mpl.py
tinywallet/tinywallet/qutilities.py
tinywallet/tinywallet/screens.py

This changeset adds the [isort](https://timothycrosley.github.io/isort/) tool to the project. It [groups and sorts](https://timothycrosley.github.io/isort/#how-does-isort-work) the import lines in each Python file.
The following changes are included:
- create a good isort configuration that doesn't conflict with black, adding it to both projects' `pyproject.toml` files;
The isort default conflicts with black, so that running both tools does not converge to a stable state: the included settings avoid this problem. The tool supports storing its config in the `pyproject.toml` file, avoiding adding yet another config file.
- add isort as a dev dependency in both projects;
This is needed so that the tool is available to both Github actions and manual usage.
- apply isort to both projects' …

Multi: sort import lines with the isort tool, and add it to both projects

---

decred/decred/dcr/rpc.py
decred/decred/dcr/txscript.py
decred/decred/dcr/wire/msgtx.py
decred/decred/util/helpers.py
decred/tests/integration/dcr/test_rpc.py

closes #45 
- addnode
- createrawssrtx
- createrawsstx
- createrawtransaction
- debuglevel
- decoderawtransaction
- decodescript
- estimatefee
- estimatesmartfee
- estimatestakediff
The create raw transactions may not be perfect yet. I'm looking into it.

rpc: Add methods

---

decred/decred/__init__.py
decred/decred/config.py
decred/decred/crypto/crypto.py
decred/decred/crypto/mnemonic.py
decred/decred/crypto/secp256k1/curve.py
decred/decred/dcr/account.py
decred/decred/dcr/calc.py
decred/decred/dcr/dcrdata.py
decred/decred/dcr/nets/__init__.py
decred/decred/dcr/txscript.py
decred/decred/dcr/wire/msgtx.py
decred/decred/dcr/wire/wire.py
decred/decred/util/database.py
decred/decred/util/encode.py
decred/decred/wallet/api.py
decred/tests/benchmark/util/test_database_benchmark.py
decred/tests/integration/dcr/test_rpc.py
decred/tests/unit/crypto/secp256k1/test_curve.py
decred/tests/unit/crypto/test_crypto.py
decred/tests/unit/crypto/test_mnemonic.py
decred/tests/unit/dcr/conftest.py
decred/tests/unit/dcr/test_dcrdata_unit.py
decred/tests/unit/dcr/test_nets.py
decred/tests/unit/dcr/test_txscript.py
decred/tests/unit/dcr/wire/test_msgtx.py
decred/tests/unit/dcr/wire/test_wire.py
decred/tests/unit/util/test_database.py

Refactor error handling in the whole library:
- create a top-level `DecredError(Exception)`;
- make all locally-defined exceptions derive from it;
- raise it in place of both `Exception` and `ValueError`;
- rename `crypto.KeyLengthException` to `KeyLengthError`;
- rename `util.database.NoValue` to `NoValueError`;
- move `dcrdata.DcrDataException` to the top of the `dcrdata.py` file;
- rename `dcrdata.DcrDataException` to `DcrDataError`;
- remove the `name` and `message` args from `DcrDataError`;
- adjust the exceptions expected from some tests.
Depends on #80.

Refactor errors

---

decred/tests/unit/dcr/conftest.py
decred/tests/unit/dcr/test_dcrdata_unit.py

Add a test for `decred.dcr.dcrdata.DcrdataPath`.
In order to avoid accessing the network, a `conftest.py` file contains two pytest fixtures that monkeypatch the `get` and `post` functions in `decred.util.tinyhttp`.
The test file is called `test_dcrdata_unit.py` because pytest wants test filenames to be globally unique, unfortunately (and undocumentedly).
Part of #70.

Add a test for DcrdataPath, and HTTP monkeypatching fixtures.

---

decred/decred/dcr/account.py
decred/decred/dcr/txscript.py

#81 improperly changed four traps from `Exception` to `DecredError`. One is reverted in #83, the remaining three are reverted here.

Revert three traps from DecredError to Exception

---

decred/decred/dcr/dcrdata.py
decred/decred/dcr/txscript.py
decred/tests/unit/dcr/test_dcrdata_unit.py

Add tests for `makeOutputs` and `checkOutput` in `dcrdata.py`. Part of #70.

tests: add tests for makeOutputs and checkOutput in dcrdata.py

---

decred/decred/dcr/account.py
decred/decred/dcr/dcrdata.py
decred/decred/dcr/txscript.py
decred/tests/unit/dcr/test_dcrdata_unit.py

This adds initial unit tests for `DcrdataBlockchain` in `dcrdata.py`. A test for subscriptions and one for UTXOs are included.
It also includes some docstring refactoring and other cleanup.
Part of #70.

Tests: initial unit tests for DcrdataBlockchain

---

decred/decred/config.py
decred/decred/dcr/dcrdata.py
decred/decred/wallet/accounts.py
decred/decred/wallet/api.py
decred/tests/unit/dcr/test_dcrdata_unit.py

This adds more UTXO unit tests in `DcrdataBlockchain`.
It also includes more cleanup like removal of the unused `DcrdataBlockchain.decodedTx` method (see line 667-668 of the diff) and `s/retreive/retrieve/` all over the codebase.
Part of #70.

tests: more unit tests for UTXOs in DcrdataBlockchain

---

decred/decred/dcr/wire/msgblock.py
decred/tests/unit/dcr/wire/test_msgblock.py

`DcrdataBlockchain` testing highlighted a bug in `dcr.wire.msgblock.BlockHeader.deserialize`. The change is shown in the first commit: https://github.com/decred/tinydecred/commit/f05d21ba9f8f42409f3bbba01ab8d9f6655e7ea8.
The `deserialize` method was only working correctly when passed a ByteArray, and failed with a raw `bytes` or `bytearray`.  The test did not catch that because it passed to `unblob` the result of `serialize`, which is a ByteArray. The test is changed to pass raw bytes to `unblob`.
(Actually I'm not sure if the fix should be applied to `deserialize` or to `unblob`: I could not locate the `encode.Blobber` API.)
The second commit improves the docstrings and converts the test to pytest format.

wire: fix a blockheader deserialize bug

---

decred/decred/dcr/account.py
decred/decred/dcr/dcrdata.py
decred/tests/unit/dcr/test_account.py
decred/tests/unit/dcr/test_dcrdata_unit.py

More tests and fixes for `dcrdata.DcrdataBlockchain`. See comments inline for detail.
`dcrdata.py` test coverage up to 92%.
Part of #70, depends on #97.

tests: more unit tests for DcrdataBlockchain

---

decred/decred/dcr/account.py
decred/decred/dcr/txscript.py
decred/tests/unit/dcr/test_txscript.py

Add checks for PubkeyHashAltTy, PubkeyAltTy, and NullDataTy. Return
NonStandardTy rather than throw an exception if no types match. This
copies dcrd's functioning.
Update tests and use a dictionary rather than a test class.
Uncomment appropriate places in getScriptClass.
account method no longer checks for an Exception.
Also changed chainParams to netParams.

txscript: Complete extractPkScriptAddrs

---

decred/decred/dcr/dcrdata.py
decred/tests/unit/dcr/test_dcrdata_unit.py

Unit tests for new methods in `dcrdata.DcrdataBlockchain`.
`dcrdata.py test` coverage *again* up to 92%. :stuck_out_tongue: 
Part of #70, depends on #98.

tests: unit tests for new methods in DcrdataBlockchain

---

decred/decred/crypto/secp256k1/curve.py
decred/decred/dcr/dcrdata.py
decred/decred/util/encode.py
decred/tests/unit/crypto/secp256k1/test_curve.py
decred/tests/unit/dcr/test_agenda.py
decred/tests/unit/util/test_encode.py

More test coverage for various modules:
`util.encode`:
- converted to pytest format;
- coverage up to 100%;
`dcr.agenda`:
- coverage up to 100%;
`crypto.secp256k1.curve`:
- coverage up to 99%.
Part of #70.

tests: more test coverage

---

decred/decred/dcr/wire/msgtx.py
decred/decred/dcr/wire/wire.py
decred/tests/unit/dcr/wire/test_msgtx.py

Take `dcr.wire.msgtx` test coverage to 100% by adding a test for `MsgTx.decodeWitness` errors.
Also move test functions from `dcr/wire/msgtx.py` to `unit/dcr/wire/test_msgtx.py`.
Finally, convert `test_msgtx.py` to pytest format.
Part of #70.

tests: complete dcr.wire.msgtx coverage

---

decred/decred/dcr/txscript.py
decred/tests/unit/dcr/test_txscript.py

Expande mergeScriots documentation. Rename chainParams to netParams.
Allow for None prevScript.
Fix mergeMultisig.

txscript: Add mergeScripts test

---

decred/decred/dcr/dcrdata.py
decred/decred/util/database.py
decred/tests/benchmark/util/test_database_benchmark.py
decred/tests/integration/dcr/test_dcrdata.py
decred/tests/unit/dcr/test_account.py
decred/tests/unit/dcr/test_dcrdata_unit.py
decred/tests/unit/util/test_database.py
decred/tests/unit/wallet/test_accounts.py

Use in-memory sqlite3 databases in all tests instead of `TemporaryDirectory` from stdlib or the `tmp_path` pytest fixture.
Also convert `tests/integration/dcr/test_dcrdata.py` to the pytest format.
The diff is somewhat messed up by the large de-indented blocks, unfortunately.
NOTE: originally I converted the tests to use the pytest's `tmpdir` feature, but then realized that using in-memory databases would be simpler and make tests faster.

tests: use in-memory databases

---

decred/decred/dcr/account.py
decred/decred/dcr/dcrdata.py
decred/tests/unit/dcr/test_account.py

Increase test coverage of `dcr/account.py`, first round. Part of #70.

tests: increase coverage of dcr/account.py

---

decred/decred/crypto/crypto.py
decred/decred/crypto/rando.py
decred/decred/wallet/simple.py
decred/decred/wallet/wallet.py
decred/tests/integration/dcr/test_dcrdata.py
decred/tests/unit/crypto/test_crypto.py
decred/tests/unit/crypto/test_rando.py
decred/tests/unit/dcr/test_account.py
decred/tests/unit/dcr/test_txscript.py
decred/tests/unit/dcr/wire/test_msgtx.py
decred/tests/unit/wallet/test_accounts.py

Currently new keys and hashes are generated with calls to `rando.generateSeed` all over the codebase, sometimes using the `KEY_SIZE` and `HASH_SIZE` constants and often wrapping the resulting byte sequence with `ByteArray`.
This PR refactors most of those calls to use four new functions instead: `newHash`, `newHashRaw`, `newKey`, `newKeyRaw`. This reduces redundancy and increases clarity about the meaning of each generated byte sequence.
It also includes a lot of formatting cleanup in `test_txscript.py`.
Please check the changes, I'm a little fuzzy about the semantic differences among seeds, hashes and keys. Do we also need two `newSeed` and `newSeedRaw` functions and a `SEED_SIZE` constant?

rando: refactor random generation of keys and hashes

---

decred/decred/dcr/txscript.py
decred/tests/unit/dcr/test_txscript.py

This is missing checks for script max size and max element size. In dcrd they are part of the exported AddData function. Should I put them in?

txscript: Add addData test

---

decred/decred/dcr/account.py
decred/tests/unit/dcr/test_account.py

The contents of `tests/unit/dcr/test_account.py` are a bit all over the place. This reorders and regroups tests so they have the same structure as the code in `account.py`. Test data used by just one test class is placed inside that class, thereby further reducing the number of top-level objects.
This helps with finding tests and code folding, enables one to only run all tests for one class, and makes adding more tests easier.
This also reorders `account.py` itself a bit by putting all functions at the top, before the classes.
Unfortunately the diff is pretty much useless, understandable given the nature of the changes.

Reorder tests/unit/dcr/test_account.py

---

decred/decred/crypto/crypto.py
decred/decred/dcr/account.py
decred/decred/dcr/calc.py
decred/decred/dcr/dcrdata.py
decred/decred/dcr/rpc.py
decred/decred/dcr/txscript.py
decred/decred/dcr/vsp.py
decred/decred/util/encode.py
decred/decred/util/helpers.py
decred/decred/wallet/accounts.py
decred/decred/wallet/wallet.py
decred/tests/unit/dcr/test_agenda.py
decred/tests/unit/dcr/test_vsp_unit.py
tinywallet/tinywallet/app.py
tinywallet/tinywallet/qutilities.py
tinywallet/tinywallet/screens.py

There are many uses of `object` in code and docstrings that seem to assume an equivalence between a Python object and a JSON object.
In Python, everything is an object. A JSON (and Javascript) object more or less translates to a dict in Python (even though JSON decoding can also return a list).
This PR changes most usages of `object` in code and docstrings to `dict`, or to `module` when network parameters are concerned. It also removes it altogether in class declarations. Finally it changes some code to be clearer and more robust.

multi: remove most references to "object" from code and docstrings

---

decred/decred/dcr/account.py
decred/tests/unit/dcr/test_account.py
decred/tests/unit/dcr/test_dcrdata_unit.py
decred/tests/unit/dcr/test_vsp_unit.py

Includes two fixes, see comments. `account.py` coverage up to 98%. Based on #119, part of #70.

tests: more coverage for dcr.account

---

decred/decred/config.py
decred/decred/crypto/crypto.py
decred/decred/dcr/account.py
decred/decred/dcr/calc.py
decred/decred/dcr/dcrdata.py
decred/decred/dcr/txscript.py
decred/decred/dcr/vsp.py
decred/decred/wallet/accounts.py
decred/tests/unit/dcr/test_account.py
decred/tests/unit/dcr/test_vsp_unit.py
tinywallet/tinywallet/app.py
tinywallet/tinywallet/screens.py

Currently the following names are used for variables referencing the network parameters modules:
`chain`, `chainParams`, `net`, `netParams`, `params`.
This PR changes them to always use `netParams`. It also updates the relevant docstrings and comments. I also made the matching comments in the wallet and tested it a bit.
I was careful to not change unrelated instances of `chain` and `params`; please check that I didn't break anything, and tell me if I missed some of the names.

multi: use "netParams" everywhere for network parameters

---

decred/decred/dcr/account.py
decred/decred/dcr/dcrdata.py
decred/decred/wallet/accounts.py
decred/tests/unit/dcr/test_account.py
decred/tests/unit/dcr/test_dcrdata_unit.py
decred/tests/unit/wallet/test_accounts.py

Adds an account discovery method to `AccountManager` that can be used on wallets restored from seed.

accounts: add account discovery

---

decred/decred/dcr/txscript.py
decred/tests/unit/dcr/test_txscript.py

Remove unused version and extra parameters. Truncate private key if over
32 bytes. Add documentation.

txscript: Add nonceRFC6979 test

---

decred/decred/dcr/rpc.py
decred/decred/util/ws.py
decred/tests/integration/dcr/test_rpc.py

An RPC client that inherits from `rpc.Client`, but uses `ws.Client` to send and receive. 
Some dcrd RPC functionality that is needed for wallets is exposed only via websockets.

rpc: add websocket dcrd rpc client

---

decred/decred/crypto/crypto.py
decred/decred/wallet/wallet.py
decred/tests/unit/crypto/test_crypto.py

The checkphrase check really should never have been there. The key params already include a hash that is used to verify the key in SecretKey.rekey. Also reworked the key authentication based on a [previous conversation](https://github.com/decred/dcrdex/pull/155#discussion_r373119966) in dcrdex.
Will need to nuke your wallet, since the old password parameters won't work anymore.

crypto: fix encryption key authentication

---

decred/decred/dcr/rpc.py
decred/decred/util/helpers.py
decred/tests/integration/dcr/test_rpc.py
decred/tests/unit/util/test_helpers.py
tinywallet/tinywallet/config.py
tinywallet/tinywallet/mpl.py
tinywallet/tinywallet/screens.py

This heavily refactors `decred/util/helpers.py` while extending its test coverage (up to 93% total). Part of #70.
All unused functions and classes have been removed.
All code used only once has been moved to the caller sites.
Tests have been written for the remaining functions that did not have any.
Here are the details.
Used by:
* `dcr/dcrdata.py`, `util/tinyhttp/py` in `decred`
* `app.py`, `qutilities.py`, `screens.py` in `tinywallet`
Used by:
* `decred/wallet/simple.py`
* `app.py, config.py` in `tinywallet`
Used by:
* `examples/plot_ticket_price.py`
* `dcr/calc.py`
* `tinywallet/mpl.py`
Used by the same file
Used by:
* `decred/tests/conftest.py`
* `unit/dcr/wire/test_wire.py`
* `tinywallet/app.py`
Used by:
* the same file
* `account.py`, `dcrdata.py`, `rpc/py`, `txscript.py` in …

util: helpers.py refactor

---

decred/decred/crypto/crypto.py
decred/decred/dcr/account.py
decred/decred/dcr/addrlib.py
decred/decred/dcr/dcrdata.py
decred/decred/dcr/txscript.py
decred/decred/dcr/vsp.py
decred/tests/integration/dcr/test_dcrdata_live.py
decred/tests/integration/dcr/test_rpc.py
decred/tests/unit/crypto/test_crypto.py
decred/tests/unit/dcr/test_account.py
decred/tests/unit/dcr/test_addrlib.py
decred/tests/unit/dcr/test_txscript.py
decred/tests/unit/wallet/test_accounts.py

Resolves #64.
- Moves the `Address*` types to a new module called `addrlib`, which is somewhat similar to **dcrd/dcrutil/address.go**. 
- Standardizes the argument type and order in address constructors. They all take a `ByteArray` as the first argument and network parameters as the second. 
- Drops extraneous constructor functions `newAddressPubKey`, `newAddressPubKeyHash`, `newAddressScriptHash`. Just use the class constructors. Moves `newAddressScriptHashFromHash` to a `staticmethod` on the `AddressScriptHash` class.
- All address types now inherit from the `Address` class, which also implements the `Blobber` API. 
- All address classes implement comparison `__eq__` methods.
- Moves `deriveChildAddress` from a method of `ExtendedKey` to a function in **account**. The crypto module does …

addrlib: move Address types to separate module

---

decred/decred/dcr/txscript.py
decred/tests/unit/dcr/test_txscript.py

Throw an exception if the passed opcode is not isSmallInt. Add
Documentation. Remove redundant conversion to int.

txscript: Add asSmallInt test

---

decred/decred/dcr/dcrdata.py
decred/tests/unit/dcr/test_dcrdata_unit.py

Improve test coverage for `dcr.dcrdata` up to 97%. Part of #70.
Including proper separation between the sending and receiving parts of `MockWebsocketClient`, and resetting the global `dcrdata._subcounter` (globals are bad).

test: more dcrdata unit tests

---

decred/decred/util/chains.py
decred/decred/wallet/accounts.py
decred/tests/unit/dcr/test_addrlib.py
decred/tests/unit/util/test_chains.py
decred/tests/unit/wallet/test_accounts.py

Bring test coverage to 100% for `utils.chains`, `wallet.accounts` and `dcr.addrlib`. Part of #70.

test: unit tests potpourri

---

decred/decred/dcr/account.py
decred/decred/dcr/addrlib.py
decred/decred/dcr/blockchain.py
decred/decred/dcr/dcrdata.py
decred/decred/dcr/rpc.py
decred/decred/util/database.py
decred/decred/util/encode.py
decred/decred/util/helpers.py
decred/tests/conftest.py
decred/tests/integration/dcr/test_blockchain_live.py
decred/tests/integration/dcr/test_rpc.py
decred/tests/unit/dcr/test_blockchain_unit.py
decred/tests/unit/util/test_database.py
decred/tests/unit/util/test_helpers.py
decred/tests/unit/wallet/test_accounts.py

Get the basic structure in place for a class called `LocalNode` that is intended for future interchangeability with `DcrdataBlockchain`, though a long ways to go. It uses the new `rpc.WebsocketClient` to access the websocket-only endpoints of the dcrd RPC needed for wallet syncing and chain monitoring. A few basic functions used for syncing accounts are in place to demonstrate how `AccountManager` and `Account` would use `LocalNode`.
Adds some needed functionality to `KeyValueDatabase`. Slice notation is supported, and there are getters for the first and last entries in a table.

blockchain: add a dcrd-based Blockchain class

---

decred/decred/dcr/account.py
decred/decred/dcr/blockchain.py
decred/decred/dcr/nets/__init__.py
decred/decred/dcr/rpc.py
decred/decred/util/database.py
decred/decred/util/ws.py
decred/decred/wallet/accounts.py
decred/tests/unit/dcr/test_account.py
decred/tests/unit/dcr/test_blockchain_unit.py
decred/tests/unit/wallet/test_accounts.py
tinywallet/tinywallet/app.py
tinywallet/tinywallet/config.py
tinywallet/tinywallet/icons/closed-eye.svg
tinywallet/tinywallet/icons/folder.svg
tinywallet/tinywallet/icons/open-eye.svg
tinywallet/tinywallet/qutilities.py
tinywallet/tinywallet/screens.py

Adds forms and settings necessary to connect to dcrd. The screen displays either a form to enter server credentials, of if already configured, a screen to turn the connection on or off or to forget the connection.
When the `LocalNode` is connected or disconnected, the `Account`s are informed and store the current `LocalNode`, but don't actually use it yet.
Adds an eye icon used as a button to toggle the echo mode of password fields.

tinywallet: connect to dcrd JSON-RPC server

---

decred/tests/unit/dcr/test_account.py
decred/tests/unit/wallet/test_accounts.py

This fixes #157 (or at least improves it).
Instead of monkeypatching I just reduced global gap limits. The slowest test is down to 3 from 8 seconds (and maybe it can be improved more), several other tests are faster too.
Interestingly, tests get even faster if we don't restore the global gap limits, and they still pass.
(I changed the rather obscure `og` prefix into `orig`.)

tests: speed them up by reducing global gap limits

---

decred/decred/dcr/addrlib.py
decred/decred/dcr/blockchain.py
decred/decred/dcr/txscript.py
decred/tests/unit/crypto/test_gcs.py
decred/tests/unit/crypto/test_mnemonic.py
decred/tests/unit/dcr/test_txscript.py

Also shorten a number of lines, and other assorted cleanup. From a PR [comment](https://github.com/decred/tinydecred/pull/150#discussion_r407512236).

multi: use crypto.RIPEMD160_SIZE where needed

---

.github/workflows/python.yml
README.md

This adds more badges to `README.md`, and also changes "project" to "package" in the workflow action definition.
The test coverage is currently static, I couldn't find a way to make it dynamic just with GitHub Actions. We'll have to subscribe the repo to a (free for FLOSS code) service like [Coveralls](https://coveralls.io/).

docs: add more badges to README.md

---

decred/decred/dcr/account.py
decred/decred/wallet/accounts.py
tinywallet/tinywallet/screens.py

Add a relay fee to settings and allow changing. The fee is not yet used.
In an attempt to keep prs small, this only adds the setting, it does not use it.
Related to #28

app: Add relay fee setting

---

decred/decred/crypto/secp256k1/curve.py
decred/tests/unit/crypto/secp256k1/test_curve.py

This improves docstrings and comments in `crypto.secp256k1.curve` and its tests, while doing some assorted cleanup too.

crypto.secp256k1.curve: clean up code and tests

---

decred/decred/crypto/secp256k1/curve.py
decred/decred/dcr/account.py
decred/decred/dcr/dcrdata.py
decred/decred/dcr/wire/msgtx.py
decred/decred/util/helpers.py
decred/tests/unit/util/test_helpers.py
tinywallet/tinywallet/screens.py

This fixes a number of unrelated issues, grouped for convenience.
It merges the `KoblitzCurve` and `Curve` classes in `crypto.secp256k1.curve`. While `Curve` is a subclass of `KoblitzCurve`, `KoblitzCurve` uses methods in `Curve`, so they're not really independent. And `KoblitzCurve` is never used directly anyway.
The other issues are explained by comments in the diff.

multi: fix a number of unrelated issues

---

tinywallet/tinywallet/app.py

Otherwise you may call shutdown on a non-existant attribute.
If you start up the app and close it without making a wallet, you will see this error currently:
```
Traceback (most recent call last):
File "tinywallet/app.py", line 155, in shutdown
if self.assetScreen is not None:
AttributeError: 'TinyWallet' object has no attribute 'assetScreen'
```

app: Check for assetScreen on shutdown.

---

.gitignore
tinywallet/.coveragerc
tinywallet/coverage-html.sh
tinywallet/poetry.lock
tinywallet/pyproject.toml
tinywallet/tests/unit/test_config.py
tinywallet/tinywallet/config.py

This adds coverage infrastructure to the `tinywallet` package. It also completes `config` and `ui` coverage, and adds `pytest-qt` to the dev dependencies. Part of #179.

tests: add coverage infrastructure to tinywallet, complete config coverage

---

decred/decred/util/database.py
tinywallet/tinywallet/screens.py

closes #172 
Rather than throwing an exception when restoring a wallet from file,
just return, allowing the user to do something else.
Create a logging helper for errors that logs to stdErr and the main ui
window.
Do not move a user's wallet file without warning. Copy it instead.
Check that the file is a sqlite database, otherwise you get stuck in a
loop until you delete or move the file manually.
The method for checking whether the database is valid comes from here: https://stackoverflow.com/questions/3888529/how-to-tell-if-sqlite-database-file-is-valid-or-not

screens: Continue on open file cancel.

---

decred/decred/util/helpers.py
decred/tests/unit/util/test_helpers.py
tinywallet/tests/unit/test_config.py
tinywallet/tinywallet/config.py
tinywallet/tinywallet/screens.py

This updates tinywallet.config to correctly parse rpclisten from the
dcrd config file, to be used as the default URL when configuring the
dcrd connection in tinywallet.
Fixes https://github.com/decred/tinydecred/issues/190

multi: Fix rpclisten config parsing
