- wallet.py
Let me know if this is useful.  If yes I will continue with this sort of pr as I go through the code.
> wallet: Update documentation

- config.py
Add method documentation. Remove bad white spaces.
I moved the comment about load() into the function documentation because it seems to be specifically about load().  Let me know if that is an unneeded change.
> config: Update documentation

- app.py
> app: Update documentation

- accounts.py
I apologize.  I ended up adding quite a bit.  Hope it is all correct.
> accounts: Update documentation

- api.py
> api: Update documentation

- crypto/crypto.py
> crypto: Update documentation

- .github/workflows/python.yml
- crypto/mnemonic.py
- pydecred/txscript.py
...by fixing two instances of undefined names. I renamed a variable in `crypto/mnemonic.py` and commented a few unreachable lines in `pydecred/txscript.py`.
> Uncomment the first flake8 in python.yml

- ui/screens.py
> Use urlparse to clean the VSP url

- ui/screens.py
> ui: use button for new address

- pydecred/rpc.py
- tests/integration/pydecred/test_rpc.py
- util/helpers.py
- util/tinyhttp.py
Adds an RPC client with a couple of methods implemented.
> pydecred: add an RPC client

- pydecred/rpc.py
- tests/integration/pydecred/test_rpc.py
rpcclient: Add methods
- validateAddress
- verifyChain
- verifyMessage
- versionResult
> rpc: add v methods

- pydecred/rpc.py
- tests/integration/pydecred/test_rpc.py
- searchrawtransactions
- sendrawtransaction (test?)
- setgenerate (test?)
- stop (test?)
- submitblock (test?)
- ticketfeeinfo
- ticketsforaddress
- ticketvwap
- txfeeinfo
I'm not sure how to test four of these. If you have any ideas, please let me know...
> RPCclient add s and t methods

- pydecred/rpc.py
- tests/integration/pydecred/test_rpc.py
- getgenerate
- gethashespersec
- getheaders
- getinfo
- getmempoolinfo
- getmininginfo
- getnettotals
- getnetworkhashps
- getnetworkinfo
- getpeerinfo
- getrawmempool
> rpc: add methods

- decred/decred/dcr/rpc.py
- decred/tests/integration/dcr/test_rpc.py
The ticket we were testing with voted. Guess I should have seen that coming...
Also remove s from RawTransactionsResult.
> Use live ticket in tests

- CONTRIBUTING.md
> tests: add a pytest mention to CONTRIBUTING.md

- decred/decred/dcr/account.py
On an incoming transaction also continue on unimplemented scripts.
> account: Continue on NotImplementedError

- decred/decred/dcr/vsp.py
- decred/tests/unit/dcr/test_vsp_unit.py
Add tests for all methods in the vsp file.
> vsp: Add unit tests

- decred/decred/dcr/txscript.py
- decred/tests/unit/dcr/test_txscript.py
Change instance of float division to integer division inside
calcMinRequiredTxRelayFee.
> txscript: Add calcMinRequiredTxRelayFee test

- decred/decred/dcr/account.py
- decred/decred/dcr/dcrdata.py
- decred/tests/unit/dcr/test_dcrdata_unit.py
Add more unit tests for the methods in dcrdata.DcrdataBlockchain dealing with blocks.
Also fix several issues uncovered by the increased test coverage.
Part of #70.
> tests: more unit tests for dcrdata.DcrdataBlockchain

- decred/decred/dcr/dcrdata.py
- decred/tests/unit/dcr/test_dcrdata_unit.py
Bug introduced in #98 that I didn't catch in testing.
> dcrdata: fix address pubsub signal receiver

- decred/decred/dcr/dcrdata.py
- decred/decred/util/ws.py
- decred/pyproject.toml
- decred/tests/integration/dcr/test_dcrdata.py
- decred/tests/integration/util/test_ws.py
- decred/tests/unit/dcr/test_dcrdata_unit.py
Partly resolves #43. Creates a websocket client class in the new **decred.util.ws** module. Adds tests for basic functionality. There's a new dev dependency, so you'll want to `poetry update` the **decred** package.
> ws: refactor websocket client

- decred/decred/wallet/accounts.py
- decred/tests/integration/util/test_ws.py
- decred/tests/unit/wallet/test_accounts.py
Take test coverage for `util.ws` and `wallet.accounts` to 100%. Part of #70.
> tests: increase coverage for util.ws and wallet.accounts.

- decred/decred/dcr/txscript.py
- decred/tests/unit/dcr/test_txscript.py
> txscript: Add bits2octets test

- decred/decred/util/helpers.py
- decred/decred/util/tinyhttp.py
- decred/tests/unit/util/test_helpers.py
- decred/tests/unit/util/test_tinyhttp.py
Refactor `util/tinyhttp.py` and add tests for it. Part of #70.
> test: refactor util/tinyhttp.py

- tinywallet/tinywallet/screens.py
> screens: Fix ticket url endpoint

- decred/decred/dcr/txscript.py
- decred/tests/unit/dcr/test_txscript.py
Add isSStx function and tests.
Tests come from here:
https://github.com/decred/dcrd/blob/52d2d2db294b4d9b01f43d69b6e847dd88233164/blockchain/stake/staketx_test.go#L23
> txscript: Add checkSStx test

- decred/decred/dcr/rpc.py
> rpc: return vin from Vin.parse

- decred/dbg-pudb.sh
- decred/decred/crypto/secp256k1/field.py
- decred/tests/unit/crypto/secp256k1/test_field.py
This syncs docstrings and comments in `crypto/secp256k1/[field.py|test_field.py]` with dcrd.
> crypto: secp256k1 field update

- CONTRIBUTING.md
- decred/tests/unit/crypto/test_crypto.py
- decred/tests/unit/crypto/test_mnemonic.py
- decred/tests/unit/dcr/test_txscript.py
- decred/tests/unit/dcr/wire/test_wire.py
Convert the remaining four test files using `unittest` from the stdlib to the pytest format.
> tests: unittest begone

- decred/decred/dcr/txscript.py
- decred/tests/unit/dcr/test_txscript.py
Add extractStakeScriptHash test.
> txscript: Add isStakeScriptHash test.

- tinywallet/tinywallet/app.py
- tinywallet/tinywallet/qutilities.py
This cleans up some docstrings, comments and some code in the `tinywallet` package.
> tinywallet: some cleanup

- tinywallet/tinywallet/app.py
- tinywallet/tinywallet/qutilities.py
- tinywallet/tinywallet/screens.py
This completes the cleanup of docstrings, comments and code in the `tinywallet` package. Based on #167.
> tinywallet: some more cleanup

- decred/decred/btc/nets/__init__.py
- decred/decred/btc/nets/mainnet.py
- decred/decred/btc/nets/regtest.py
- decred/decred/btc/nets/simnet.py
- decred/decred/btc/nets/testnet.py
- decred/tests/unit/btc/test_nets_btc.py
Step 1 of multi-asset. BTC configuration files for 4 networks.
> btc: add btc network configuration parameters

- decred/decred/dcr/wire/msgverack.py
- decred/tests/unit/dcr/wire/test_msgverack.py
SPV Peer response for MsgVersion message.
> wire: add MsgVerAck type

- decred/decred/dcr/wire/msgtx.py
- decred/decred/dcr/wire/netaddress.py
- decred/decred/dcr/wire/wire.py
- decred/tests/unit/dcr/wire/test_netaddress.py
NetAddress  will be used in upcoming SPV peer work.
> dcr/wire: add NetAddress type

- decred/decred/dcr/wire/msgping.py
- decred/decred/dcr/wire/msgpong.py
- decred/tests/unit/dcr/wire/test_msgping.py
- decred/tests/unit/dcr/wire/test_msgpong.py
> wire: add MsgPing and MsgPong types

- decred/decred/dcr/wire/msgblock.py
- decred/decred/dcr/wire/msgtx.py
- decred/decred/dcr/wire/msgversion.py
- decred/tests/unit/dcr/wire/test_msgversion.py
Needed for upcoming SPV peer. Depends on #185.
> wire: add MsgVersion type
